Updating Documention
Flam3rboy/missing-native-js-functions pull request #21
Opened 2022-12-21 10:35 UTC by xNaCly

## Abstract:
This pull request serves the purpose of improving the documentation and the workflow of adding examples, comments, and descriptions by moving away from manually writing HTML documentation to [jsdoc](https://github.com/jsdoc/jsdoc) and generating the documentation using [typedoc](https://typedoc.org/).

### Infos:
#### How to generate the new documentation:
```
npm i -g typedoc
git clone https://github.com/trantlabs/missing-native-js-functions
typedoc src/*.ts
```
The generated documentation can be found in `./docs`

## Screenshots of the generated documentation
### Readme:
![grafik](https://user-images.githubusercontent.com/47723417/208883078-f30ac727-b464-42ab-8976-5d517af5268a.png)
### Description and Comments for methods:
#### Screenshot
![grafik](https://user-images.githubusercontent.com/47723417/208883143-4faf4c8d-8841-4347-89e8-1723e5dc0f60.png)
#### Corresponding jsdoc function comments:
![grafik](https://user-images.githubusercontent.com/47723417/208883548-e0977837-d799-4382-a7af-9547aeafd38f.png)

## Fixed bugs:
While writing these comments I came across some bugs which I promptly fixed:
- wrong return type for `String.equalsIgnoreCase`, changed from `string` to `boolean` 

## List of changes:
- removed old documentation
- wrote jsdoc for:
  - Array.ts
  - Date.ts
  - Global.ts
  - Math.ts
  - Number.ts
  - Object.ts
  - Promise.ts
  - String.ts
  - Util.ts
- removed documentation from Readme

2022-12-21 10:41 UTC, Intevel requested changes

2022-12-21 10:41 UTC, Intevel commented on README.md
> +mnjsf delivers functions missing from JavaScript
Maybe add a `native` before `JavaScript`?

2022-12-21 10:42 UTC, Intevel approved these changes

2022-12-21 11:28 UTC, SamuelScheit approved these changes

2022-12-21 12:17 UTC, xNaCly commented
## Switching Interfaces
Im currently thinking of switching to the `Date` interface, away from the `DateConstructor` interface, due to the fact, that i wasn't able to call the defined functions on the Date without creating an instance.:
![image](https://user-images.githubusercontent.com/47723417/208902560-53ab1a53-733a-4b05-9080-c19a755b7189.png)

I also wasn't able to see any doc comments on these functions. It also doesn't make sense to define functions which rely on an instance, such as `setInstance` and `isInPast` on a constructor.

## Fixing bugs
Also, the `DateConstructor.setTimezone` function does not work as intended, it always returns a local date:
```ts
	setTimezone: function (timezone: string) {
		return new Date(
			this.toLocaleString("en-US", {
				timezone,
			})
		);
	},
```
According to the docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#options we should be able to fix this by replacing `timezone` in the options with `timeZone`.

Test in the browser dev tools:
![image](https://user-images.githubusercontent.com/47723417/208901938-a8028dd7-9edc-4734-94fb-89b8a6ac43e2.png)

@SamuelScheit @Intevel

2022-12-22 08:30 UTC, Intevel requested changes

2022-12-22 08:30 UTC, Intevel commented on src/Array.ts
> +		return this; // .filter((e) => e !== elem);
Remove comment

2022-12-22 08:30 UTC, Intevel commented on src/Object.ts
> +			// @ts-ignore
Use ts-expect-error instead of ts-ignore

2022-12-22 09:02 UTC, Intevel approved these changes

2022-12-22 09:28 UTC, SamuelScheit approved these changes

2022-12-22 09:32 UTC, merged